### ISSUE TITLE
As a user I should be able to view which other users or visitors have looked at my profile

### ISSUE THREAD

**Issue by Dragon1320** [bandsy/profile#7]
Allowing to view all activity on a user's profile allows for better privacy as well as finding other users which may be of interest.

Acceptance criteria:
- User can view a list of all users that have accessed their profile including:
  - Number of views.
  - Times at which the profile was viewed.
  - Their compatibility and/or similarities with the user.
- User can view the number of visitors that have accessed their profile.

**Comment by rlarkin212** [comment]
weeb trash
